# START CUSTOM ALIASES


# Directory aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias www='clear; cd /var/www/html/; ls'
alias md='mkdir -p'
alias rd='rmdir'
alias ls='ls -hF --color=auto --group-directories-first'
alias la='ls -hFA --color=auto --group-directories-first'
alias ll='ls -hFAl --color=auto --group-directories-first'

alias sb='source ~/.bashrc'
alias s='source'

# Docker
alias dk='docker'
alias dka='docker attach'
alias dkb='docker build'
alias dkd='docker diff'
alias dkdf='docker system df'
alias dke='docker exec'
alias dkE='docker exec -it'
alias dkh='docker history'
alias dki='docker images'
alias dkin='docker inspect'
alias dkim='docker import'
alias dkk='docker kill'
alias dkl='docker logs'
alias dkli='docker login'
alias dklo='docker logout'
alias dkls='docker ps'
alias dkp='docker pause'
alias dkP='docker unpause'
alias dkpl='docker pull'
alias dkph='docker push'
alias dkps='docker ps'
alias dkpsa='docker ps -a'
alias dkr='docker run'
alias dkR='docker run -it --rm'
alias dkRe='docker run -it --rm --entrypoint /bin/bash'
alias dkRM='docker system prune'
alias dkrm='docker rm'
alias dkrmi='docker rmi'
alias dkrn='docker rename'
alias dks='docker start'
alias dkS='docker restart'
alias dkss='docker stats'
alias dksv='docker save'
alias dkt='docker tag'
alias dktop='docker top'
alias dkup='docker update'
alias dkV='docker volume'
alias dkv='docker version'
alias dkw='docker wait'
alias dkx='docker stop'

# Program aliases
alias n='nano'
alias sn='sudo nano'
alias m='micro'
alias sm='sudo micro'
alias t='touch'
alias st='sudo touch'
alias targz='tar -zcvf'
alias untargz='tar -zxvf'
alias wget='wget -c'
alias ping='ping -c 5'
alias top='htop'

# Git aliases
alias add='git add .'
alias branch='git branch'
alias checkout='git checkout'
alias clone='git clone'
alias commit='git commit -m'
alias pull='git pull'
alias push='git push'
alias reset='git reset'
alias status='git status'

# System aliases
alias yum='yum -y'
alias sc='systemctl'
alias scd='sc disable'
alias sce='sc enable'
alias scr='sc restart'
alias scs='sc status'
alias scx='sc stop'

# Miscellaneous aliases
alias root='sudo -i'
alias fuck='sudo'
alias fucking='sudo'
alias c='clear'
alias x='exit'

# END CUSTOM ALIASES
